export interface Seedling {
  id: string
  name: string
  price: number
  icon: string
  category: string
  careGuide?: {
    watering: string
    sunlight: string
    soil: string
    temperature: string
    fertilizer: string
    spacing: string
    timeToFruit: string
    pests: string
  }
}

export const seedlings: Seedling[] = [
  // Mangoes
  {
    id: "1",
    name: "Grafted Tommy Mango",
    price: 200,
    icon: "🥭",
    category: "mango",
    careGuide: {
      watering: "Annual rainfall of 850 to 1000mm is sufficient for mango cultivation. It should be noted that rainfall during flowering season reduces fruit setting. After the plant is well established it can tolerate drought especially when its tap root reaches the water table. Water deeply once a week during dry season.",
      sunlight: "Requires full sun (6-8 hours minimum) for optimal fruit production. Pruning opens up the trees for aeration and penetration of sun rays, which is important for pest and disease management.",
      soil: "Mango plants are adapted to many soil types but prefer deep (at least 3m) soils that are fertile and well drained with optimum pH of 5.5 to 7.5. Planting: Dig holes with dimensions 2 ft length by 2 ft width by 2 ft depth. Mix a bucket full of farmyard manure with topsoil at planting stage. Water the plant after planting if soil isn't wet enough.",
      temperature: "Mango do best on average annual temperature of between 15 to 30 degrees centigrade.",
      fertilizer: "During flowering, mangoes need high amounts of potassium to trigger flowering, flower retention and good development of fruits. Inadequate potassium leads to heavy flower abortion and unhealthy fruit set and development. Apply balanced fertilizer (10-10-10) quarterly. Use NPK 2:1:2 during fruiting.",
      spacing: "Plant 8-10 meters apart for mature trees.",
      timeToFruit: "2-3 years from grafted plant. Peak production at 5-7 years.",
      pests: "Pests: Mango Seed Weevil (adults are dark brown with grey markings, 6-9cm long, lay eggs on young fruits), Mango Gall Fly (causes wart-like galls on leaves), Mealybugs (tiny soft-bodied insects causing sooty mould), Mango Scales (limpet-like insects with waxy covering), Thrips (cause flower abortion and rusty appearance on fruits), Red Spider Mites (puncture plant cells and scar young fruit), Mango Fruit Fly (most important pest, causes fruit rotting). Diseases: Powdery Mildew (white spots on leaves and flowers), Anthracnose (dark sunken lesions on fruits and leaves), Die Back (drying of twigs from top to bottom). Nutritional Deficiencies: Potassium deficiency (scorching of leaf margin), Boron deficiency (flower abortion and fruit cracking), Zinc deficiency (small leaves with margins bent).",
    },
  },
  {
    id: "2",
    name: "Grafted Apple Mango",
    price: 200,
    icon: "🥭",
    category: "mango",
    careGuide: {
      watering: "Annual rainfall of 850 to 1000mm is sufficient for mango cultivation. It should be noted that rainfall during flowering season reduces fruit setting. After the plant is well established it can tolerate drought especially when its tap root reaches the water table. Water regularly during growing season, reduce in dry season.",
      sunlight: "Full sun exposure (6+ hours daily). Pruning opens up the trees for aeration and penetration of sun rays, which is important for pest and disease management.",
      soil: "Mango plants are adapted to many soil types but prefer deep (at least 3m) soils that are fertile and well drained with optimum pH of 5.5 to 7.5. Planting: Dig holes with dimensions 2 ft length by 2 ft width by 2 ft depth. Mix a bucket full of farmyard manure with topsoil at planting stage. Water the plant after planting if soil isn't wet enough.",
      temperature: "Mango do best on average annual temperature of between 15 to 30 degrees centigrade.",
      fertilizer: "During flowering, mangoes need high amounts of potassium to trigger flowering, flower retention and good development of fruits. Inadequate potassium leads to heavy flower abortion and unhealthy fruit set and development. Apply NPK 10-5-20 during fruiting season.",
      spacing: "8-10 meters between trees.",
      timeToFruit: "2-4 years from grafted plant.",
      pests: "Pests: Mango Seed Weevil (adults are dark brown with grey markings, 6-9cm long, lay eggs on young fruits), Mango Gall Fly (causes wart-like galls on leaves), Mealybugs (tiny soft-bodied insects causing sooty mould), Mango Scales (limpet-like insects with waxy covering), Thrips (cause flower abortion and rusty appearance on fruits), Red Spider Mites (puncture plant cells and scar young fruit), Mango Fruit Fly (most important pest, causes fruit rotting). Diseases: Powdery Mildew (white spots on leaves and flowers), Anthracnose (dark sunken lesions on fruits and leaves), Die Back (drying of twigs from top to bottom). Nutritional Deficiencies: Potassium deficiency (scorching of leaf margin), Boron deficiency (flower abortion and fruit cracking), Zinc deficiency (small leaves with margins bent).",
    },
  },
  {
    id: "3",
    name: "Grafted Van Dyke Mango",
    price: 200,
    icon: "🥭",
    category: "mango",
    careGuide: {
      watering: "Annual rainfall of 850 to 1000mm is sufficient for mango cultivation. It should be noted that rainfall during flowering season reduces fruit setting. After the plant is well established it can tolerate drought especially when its tap root reaches the water table. Deep watering weekly in hot season.",
      sunlight: "Needs strong sunlight for better yields. Pruning opens up the trees for aeration and penetration of sun rays, which is important for pest and disease management.",
      soil: "Mango plants are adapted to many soil types but prefer deep (at least 3m) soils that are fertile and well drained with optimum pH of 5.5 to 7.5. Planting: Dig holes with dimensions 2 ft length by 2 ft width by 2 ft depth. Mix a bucket full of farmyard manure with topsoil at planting stage. Water the plant after planting if soil isn't wet enough.",
      temperature: "Mango do best on average annual temperature of between 15 to 30 degrees centigrade.",
      fertilizer: "During flowering, mangoes need high amounts of potassium to trigger flowering, flower retention and good development of fruits. Inadequate potassium leads to heavy flower abortion and unhealthy fruit set and development. Apply organic manure and balanced NPK.",
      spacing: "10 meters between trees.",
      timeToFruit: "3-4 years.",
      pests: "Pests: Mango Seed Weevil (adults are dark brown with grey markings, 6-9cm long, lay eggs on young fruits), Mango Gall Fly (causes wart-like galls on leaves), Mealybugs (tiny soft-bodied insects causing sooty mould), Mango Scales (limpet-like insects with waxy covering), Thrips (cause flower abortion and rusty appearance on fruits), Red Spider Mites (puncture plant cells and scar young fruit), Mango Fruit Fly (most important pest, causes fruit rotting). Diseases: Powdery Mildew (white spots on leaves and flowers), Anthracnose (dark sunken lesions on fruits and leaves), Die Back (drying of twigs from top to bottom). Nutritional Deficiencies: Potassium deficiency (scorching of leaf margin), Boron deficiency (flower abortion and fruit cracking), Zinc deficiency (small leaves with margins bent).",
    },
  },
  {
    id: "4",
    name: "Grafted Ngowe Mango",
    price: 200,
    icon: "🥭",
    category: "mango",
    careGuide: {
      watering: "Annual rainfall of 850 to 1000mm is sufficient for mango cultivation. It should be noted that rainfall during flowering season reduces fruit setting. After the plant is well established it can tolerate drought especially when its tap root reaches the water table. Moderate watering, drought tolerant once established.",
      sunlight: "Full sun required. Pruning opens up the trees for aeration and penetration of sun rays, which is important for pest and disease management.",
      soil: "Mango plants are adapted to many soil types but prefer deep (at least 3m) soils that are fertile and well drained with optimum pH of 5.5 to 7.5. Planting: Dig holes with dimensions 2 ft length by 2 ft width by 2 ft depth. Mix a bucket full of farmyard manure with topsoil at planting stage. Water the plant after planting if soil isn't wet enough.",
      temperature: "Mango do best on average annual temperature of between 15 to 30 degrees centigrade.",
      fertilizer: "During flowering, mangoes need high amounts of potassium to trigger flowering, flower retention and good development of fruits. Inadequate potassium leads to heavy flower abortion and unhealthy fruit set and development. Minimal fertilizer needs once established, but ensure adequate potassium during flowering.",
      spacing: "8-10 meters apart.",
      timeToFruit: "2-3 years from grafted plant.",
      pests: "Pests: Mango Seed Weevil (adults are dark brown with grey markings, 6-9cm long, lay eggs on young fruits), Mango Gall Fly (causes wart-like galls on leaves), Mealybugs (tiny soft-bodied insects causing sooty mould), Mango Scales (limpet-like insects with waxy covering), Thrips (cause flower abortion and rusty appearance on fruits), Red Spider Mites (puncture plant cells and scar young fruit), Mango Fruit Fly (most important pest, causes fruit rotting). Diseases: Powdery Mildew (white spots on leaves and flowers), Anthracnose (dark sunken lesions on fruits and leaves), Die Back (drying of twigs from top to bottom). Nutritional Deficiencies: Potassium deficiency (scorching of leaf margin), Boron deficiency (flower abortion and fruit cracking), Zinc deficiency (small leaves with margins bent).",
    },
  },
  {
    id: "5",
    name: "Alphonso Mango",
    price: 400,
    icon: "🥭",
    category: "mango",
    careGuide: {
      watering: "Annual rainfall of 850 to 1000mm is sufficient for mango cultivation. It should be noted that rainfall during flowering season reduces fruit setting. After the plant is well established it can tolerate drought especially when its tap root reaches the water table. Regular watering, especially during flowering and fruiting.",
      sunlight: "8+ hours of direct sunlight daily. Pruning opens up the trees for aeration and penetration of sun rays, which is important for pest and disease management.",
      soil: "Mango plants are adapted to many soil types but prefer deep (at least 3m) soils that are fertile and well drained with optimum pH of 5.5 to 7.5. Planting: Dig holes with dimensions 2 ft length by 2 ft width by 2 ft depth. Mix a bucket full of farmyard manure with topsoil at planting stage. Water the plant after planting if soil isn't wet enough.",
      temperature: "Mango do best on average annual temperature of between 15 to 30 degrees centigrade.",
      fertilizer: "During flowering, mangoes need high amounts of potassium to trigger flowering, flower retention and good development of fruits. Inadequate potassium leads to heavy flower abortion and unhealthy fruit set and development. Organic and inorganic fertilizers, apply 3x yearly with emphasis on potassium during flowering.",
      spacing: "10 meters between trees.",
      timeToFruit: "2-3 years from grafted plant.",
      pests: "Pests: Mango Seed Weevil (adults are dark brown with grey markings, 6-9cm long, lay eggs on young fruits), Mango Gall Fly (causes wart-like galls on leaves), Mealybugs (tiny soft-bodied insects causing sooty mould), Mango Scales (limpet-like insects with waxy covering), Thrips (cause flower abortion and rusty appearance on fruits), Red Spider Mites (puncture plant cells and scar young fruit), Mango Fruit Fly (most important pest, causes fruit rotting). Diseases: Powdery Mildew (white spots on leaves and flowers), Anthracnose (dark sunken lesions on fruits and leaves - susceptible variety), Die Back (drying of twigs from top to bottom). Nutritional Deficiencies: Potassium deficiency (scorching of leaf margin), Boron deficiency (flower abortion and fruit cracking), Zinc deficiency (small leaves with margins bent).",
    },
  },

  // Citrus
  {
    id: "6",
    name: "Grafted Pixies Orange",
    price: 300,
    icon: "🍊",
    category: "citrus",
    careGuide: {
      watering: "Citrus trees should be planted in a sunny and wind-protected area. They can tolerate high temperatures provided the trees are well supplied with soil moisture. Water regularly, 2-3 times weekly during dry season. Water the plant after planting if soil isn't wet enough.",
      sunlight: "Full sun (8+ hours) for sweet, quality fruit. Citrus trees should be planted in a sunny and wind-protected area, and in frost-free regions because they cannot tolerate severe frosts.",
      soil: "Citrus can be grown in a wide range of soil types. However, for best results, they should be grown in well-drained soils, which are fertile, well-aerated and with a pH of between 6-6.5. The growth, development and production of citrus plant depends on the physical characteristics of the soil such as drainage, water-holding capacity, structure, soil depth, and the degree to which water can infiltrate the soil. Planting: Dig holes with dimensions 2 ft length by 2 ft width by 2 ft depth. Mix a bucket full of farmyard manure with topsoil at planting stage.",
      temperature: "Warm climate (15-28°C). Citrus trees should be planted in frost-free regions because they cannot tolerate severe frosts. They can tolerate high temperatures provided the trees are well supplied with soil moisture.",
      fertilizer: "In order to remain healthy and produce optimally, the plants require sufficient nutrients, both macro and micronutrients. Nutrients that are needed in relatively large amounts are called the macronutrients. Basal and foliar fertilizers should therefore be applied in order to ensure effective nutrient supply to the plants. Apply citrus fertilizer 3-4 times yearly.",
      spacing: "Spacing: 4m by 4m. 256 pieces per acre.",
      timeToFruit: "2.5 to 3 years.",
      pests: "Pests: False coddling moth (larvae burrow into fruit rind causing discoloration and premature ripening), Aphids (suck sap causing puckered marks, yellowing and twisting of leaves, honeydew excretion), Orange dog caterpillar (large 1.5-2 inch brown caterpillar that defoliates trees), Citrus whiteflies (tiny white winged insects feeding on underside of leaves, excrete honeydew), Fruit fly (adults deposit eggs under fruit skin, maggots feed on flesh causing rot), Citrus leafminer (larvae feed on young foliage creating silvery tunnels), Brown soft scale (small non-mobile insects attached to wood and foliage, cause yellowing and leaf drop), Citrus thrips (tiny orange or pale yellow insects causing shriveled buds and distorted leaves), Citrus bud mite (exceptionally small mite hiding in flower buds causing malformed growth). Diseases: Citrus canker (highly contagious bacterial infection with yellow halo-like lesions), Sooty mold (blackening fungus from honeydew secretions), Greasy spot (fungal disease with yellowish-brownish blister spots), Anthracnose (causes twig dieback and dark staining on fruit), Bacterial blast (black lesions in leaf petiole causing leaf curl and drop), Root Rot/Brown Rot/Collar rot (soil-inhabiting fungus causing dark brown patches on trunk), Citrus greening (bacterium spread by psyllids causing yellowing and stunted growth), Powdery mildew (white powdery spores on leaves), Citrus gummosis (fungal infection on trunk causing amber-colored gum). Nutritional Deficiencies: Nitrogen deficiency (light green to yellow foliage, yellow vein chlorosis). Pruning: Dead wood must be removed regularly. When trees become too big and start growing into one another, pruning is recommended. Branches touching the ground should be removed. Weeding: Keep the area under the canopy free from weeds as they compete for nutrients and water and harbour pathogens.",
    },
  },
  {
    id: "7",
    name: "Grafted Washington Orange",
    price: 200,
    icon: "🍊",
    category: "citrus",
    careGuide: {
      watering: "Citrus trees should be planted in a sunny and wind-protected area. They can tolerate high temperatures provided the trees are well supplied with soil moisture. Regular irrigation needed, especially when fruiting. Water the plant after planting if soil isn't wet enough.",
      sunlight: "Requires full sunlight. Citrus trees should be planted in a sunny and wind-protected area, and in frost-free regions because they cannot tolerate severe frosts.",
      soil: "Citrus can be grown in a wide range of soil types. However, for best results, they should be grown in well-drained soils, which are fertile, well-aerated and with a pH of between 6-6.5. The growth, development and production of citrus plant depends on the physical characteristics of the soil such as drainage, water-holding capacity, structure, soil depth, and the degree to which water can infiltrate the soil. Planting: Dig holes with dimensions 2 ft length by 2 ft width by 2 ft depth. Mix a bucket full of farmyard manure with topsoil at planting stage.",
      temperature: "Thrives in warm regions (18-30°C). Citrus trees should be planted in frost-free regions because they cannot tolerate severe frosts. They can tolerate high temperatures provided the trees are well supplied with soil moisture.",
      fertilizer: "In order to remain healthy and produce optimally, the plants require sufficient nutrients, both macro and micronutrients. Nutrients that are needed in relatively large amounts are called the macronutrients. Basal and foliar fertilizers should therefore be applied in order to ensure effective nutrient supply to the plants. Apply NPK 8-8-8 or citrus-specific fertilizer.",
      spacing: "4m by 4m. 256 pieces per acre.",
      timeToFruit: "2.5 to 3 years.",
      pests: "Pests: False coddling moth (larvae burrow into fruit rind causing discoloration and premature ripening), Aphids (suck sap causing puckered marks, yellowing and twisting of leaves, honeydew excretion), Orange dog caterpillar (large 1.5-2 inch brown caterpillar that defoliates trees), Citrus whiteflies (tiny white winged insects feeding on underside of leaves, excrete honeydew), Fruit fly (adults deposit eggs under fruit skin, maggots feed on flesh causing rot), Citrus leafminer (larvae feed on young foliage creating silvery tunnels), Brown soft scale (small non-mobile insects attached to wood and foliage, cause yellowing and leaf drop), Citrus thrips (tiny orange or pale yellow insects causing shriveled buds and distorted leaves), Citrus bud mite (exceptionally small mite hiding in flower buds causing malformed growth). Diseases: Citrus canker (highly contagious bacterial infection with yellow halo-like lesions), Sooty mold (blackening fungus from honeydew secretions), Greasy spot (fungal disease with yellowish-brownish blister spots), Anthracnose (causes twig dieback and dark staining on fruit), Bacterial blast (black lesions in leaf petiole causing leaf curl and drop), Root Rot/Brown Rot/Collar rot (soil-inhabiting fungus causing dark brown patches on trunk), Citrus greening (bacterium spread by psyllids causing yellowing and stunted growth), Powdery mildew (white powdery spores on leaves), Citrus gummosis (fungal infection on trunk causing amber-colored gum). Nutritional Deficiencies: Nitrogen deficiency (light green to yellow foliage, yellow vein chlorosis). Pruning: Dead wood must be removed regularly. When trees become too big and start growing into one another, pruning is recommended. Branches touching the ground should be removed. Weeding: Keep the area under the canopy free from weeds as they compete for nutrients and water and harbour pathogens.",
    },
  },
  {
    id: "8",
    name: "Grafted Valencia Orange",
    price: 200,
    icon: "🍊",
    category: "citrus",
    careGuide: {
      watering: "Citrus trees should be planted in a sunny and wind-protected area. They can tolerate high temperatures provided the trees are well supplied with soil moisture. Consistent watering during growing season. Water the plant after planting if soil isn't wet enough.",
      sunlight: "Full sun essential. Citrus trees should be planted in a sunny and wind-protected area, and in frost-free regions because they cannot tolerate severe frosts.",
      soil: "Citrus can be grown in a wide range of soil types. However, for best results, they should be grown in well-drained soils, which are fertile, well-aerated and with a pH of between 6-6.5. The growth, development and production of citrus plant depends on the physical characteristics of the soil such as drainage, water-holding capacity, structure, soil depth, and the degree to which water can infiltrate the soil. Planting: Dig holes with dimensions 2 ft length by 2 ft width by 2 ft depth. Mix a bucket full of farmyard manure with topsoil at planting stage.",
      temperature: "Warm climate (20-32°C). Citrus trees should be planted in frost-free regions because they cannot tolerate severe frosts. They can tolerate high temperatures provided the trees are well supplied with soil moisture.",
      fertilizer: "In order to remain healthy and produce optimally, the plants require sufficient nutrients, both macro and micronutrients. Nutrients that are needed in relatively large amounts are called the macronutrients. Basal and foliar fertilizers should therefore be applied in order to ensure effective nutrient supply to the plants. Balanced NPK or citrus fertilizer.",
      spacing: "4m by 4m. 256 pieces per acre.",
      timeToFruit: "2.5 to 3 years.",
      pests: "Pests: False coddling moth (larvae burrow into fruit rind causing discoloration and premature ripening), Aphids (suck sap causing puckered marks, yellowing and twisting of leaves, honeydew excretion), Orange dog caterpillar (large 1.5-2 inch brown caterpillar that defoliates trees), Citrus whiteflies (tiny white winged insects feeding on underside of leaves, excrete honeydew), Fruit fly (adults deposit eggs under fruit skin, maggots feed on flesh causing rot), Citrus leafminer (larvae feed on young foliage creating silvery tunnels), Brown soft scale (small non-mobile insects attached to wood and foliage, cause yellowing and leaf drop), Citrus thrips (tiny orange or pale yellow insects causing shriveled buds and distorted leaves), Citrus bud mite (exceptionally small mite hiding in flower buds causing malformed growth). Diseases: Citrus canker (highly contagious bacterial infection with yellow halo-like lesions), Sooty mold (blackening fungus from honeydew secretions), Greasy spot (fungal disease with yellowish-brownish blister spots), Anthracnose (causes twig dieback and dark staining on fruit), Bacterial blast (black lesions in leaf petiole causing leaf curl and drop), Root Rot/Brown Rot/Collar rot (soil-inhabiting fungus causing dark brown patches on trunk), Citrus greening (bacterium spread by psyllids causing yellowing and stunted growth), Powdery mildew (white powdery spores on leaves), Citrus gummosis (fungal infection on trunk causing amber-colored gum). Nutritional Deficiencies: Nitrogen deficiency (light green to yellow foliage, yellow vein chlorosis). Pruning: Dead wood must be removed regularly. When trees become too big and start growing into one another, pruning is recommended. Branches touching the ground should be removed. Weeding: Keep the area under the canopy free from weeds as they compete for nutrients and water and harbour pathogens.",
    },
  },
  {
    id: "9",
    name: "Grafted Tangerine",
    price: 200,
    icon: "🍊",
    category: "citrus",
    careGuide: {
      watering: "Citrus trees should be planted in a sunny and wind-protected area. They can tolerate high temperatures provided the trees are well supplied with soil moisture. Water moderately, avoid waterlogging. Water the plant after planting if soil isn't wet enough.",
      sunlight: "Full sun (6-8 hours). Citrus trees should be planted in a sunny and wind-protected area, and in frost-free regions because they cannot tolerate severe frosts.",
      soil: "Citrus can be grown in a wide range of soil types. However, for best results, they should be grown in well-drained soils, which are fertile, well-aerated and with a pH of between 6-6.5. The growth, development and production of citrus plant depends on the physical characteristics of the soil such as drainage, water-holding capacity, structure, soil depth, and the degree to which water can infiltrate the soil. Planting: Dig holes with dimensions 2 ft length by 2 ft width by 2 ft depth. Mix a bucket full of farmyard manure with topsoil at planting stage.",
      temperature: "Moderate warm (15-28°C). Citrus trees should be planted in frost-free regions because they cannot tolerate severe frosts. They can tolerate high temperatures provided the trees are well supplied with soil moisture.",
      fertilizer: "In order to remain healthy and produce optimally, the plants require sufficient nutrients, both macro and micronutrients. Nutrients that are needed in relatively large amounts are called the macronutrients. Basal and foliar fertilizers should therefore be applied in order to ensure effective nutrient supply to the plants. NPK 10-5-5 during growth phase.",
      spacing: "4m by 4m. 256 pieces per acre.",
      timeToFruit: "2.5 to 3 years.",
      pests: "Pests: False coddling moth (larvae burrow into fruit rind causing discoloration and premature ripening), Aphids (suck sap causing puckered marks, yellowing and twisting of leaves, honeydew excretion), Orange dog caterpillar (large 1.5-2 inch brown caterpillar that defoliates trees), Citrus whiteflies (tiny white winged insects feeding on underside of leaves, excrete honeydew), Fruit fly (adults deposit eggs under fruit skin, maggots feed on flesh causing rot), Citrus leafminer (larvae feed on young foliage creating silvery tunnels), Brown soft scale (small non-mobile insects attached to wood and foliage, cause yellowing and leaf drop), Citrus thrips (tiny orange or pale yellow insects causing shriveled buds and distorted leaves), Citrus bud mite (exceptionally small mite hiding in flower buds causing malformed growth). Diseases: Citrus canker (highly contagious bacterial infection with yellow halo-like lesions), Sooty mold (blackening fungus from honeydew secretions), Greasy spot (fungal disease with yellowish-brownish blister spots), Anthracnose (causes twig dieback and dark staining on fruit), Bacterial blast (black lesions in leaf petiole causing leaf curl and drop), Root Rot/Brown Rot/Collar rot (soil-inhabiting fungus causing dark brown patches on trunk), Citrus greening (bacterium spread by psyllids causing yellowing and stunted growth), Powdery mildew (white powdery spores on leaves), Citrus gummosis (fungal infection on trunk causing amber-colored gum). Nutritional Deficiencies: Nitrogen deficiency (light green to yellow foliage, yellow vein chlorosis). Pruning: Dead wood must be removed regularly. When trees become too big and start growing into one another, pruning is recommended. Branches touching the ground should be removed. Weeding: Keep the area under the canopy free from weeds as they compete for nutrients and water and harbour pathogens.",
    },
  },
  {
    id: "10",
    name: "Minneola Tangelo Orange",
    price: 250,
    icon: "🍊",
    category: "citrus",
    careGuide: {
      watering: "Citrus trees should be planted in a sunny and wind-protected area. They can tolerate high temperatures provided the trees are well supplied with soil moisture. Regular watering during dry periods. Water the plant after planting if soil isn't wet enough.",
      sunlight: "Full sun required. Citrus trees should be planted in a sunny and wind-protected area, and in frost-free regions because they cannot tolerate severe frosts.",
      soil: "Citrus can be grown in a wide range of soil types. However, for best results, they should be grown in well-drained soils, which are fertile, well-aerated and with a pH of between 6-6.5. The growth, development and production of citrus plant depends on the physical characteristics of the soil such as drainage, water-holding capacity, structure, soil depth, and the degree to which water can infiltrate the soil. Planting: Dig holes with dimensions 2 ft length by 2 ft width by 2 ft depth. Mix a bucket full of farmyard manure with topsoil at planting stage.",
      temperature: "Warm climate (18-32°C). Citrus trees should be planted in frost-free regions because they cannot tolerate severe frosts. They can tolerate high temperatures provided the trees are well supplied with soil moisture.",
      fertilizer: "In order to remain healthy and produce optimally, the plants require sufficient nutrients, both macro and micronutrients. Nutrients that are needed in relatively large amounts are called the macronutrients. Basal and foliar fertilizers should therefore be applied in order to ensure effective nutrient supply to the plants. Citrus fertilizer 3x yearly.",
      spacing: "4m by 4m. 256 pieces per acre.",
      timeToFruit: "2.5 to 3 years.",
      pests: "Pests: False coddling moth (larvae burrow into fruit rind causing discoloration and premature ripening), Aphids (suck sap causing puckered marks, yellowing and twisting of leaves, honeydew excretion), Orange dog caterpillar (large 1.5-2 inch brown caterpillar that defoliates trees), Citrus whiteflies (tiny white winged insects feeding on underside of leaves, excrete honeydew), Fruit fly (adults deposit eggs under fruit skin, maggots feed on flesh causing rot), Citrus leafminer (larvae feed on young foliage creating silvery tunnels), Brown soft scale (small non-mobile insects attached to wood and foliage, cause yellowing and leaf drop), Citrus thrips (tiny orange or pale yellow insects causing shriveled buds and distorted leaves), Citrus bud mite (exceptionally small mite hiding in flower buds causing malformed growth). Diseases: Citrus canker (highly contagious bacterial infection with yellow halo-like lesions), Sooty mold (blackening fungus from honeydew secretions), Greasy spot (fungal disease with yellowish-brownish blister spots), Anthracnose (causes twig dieback and dark staining on fruit), Bacterial blast (black lesions in leaf petiole causing leaf curl and drop), Root Rot/Brown Rot/Collar rot (soil-inhabiting fungus causing dark brown patches on trunk), Citrus greening (bacterium spread by psyllids causing yellowing and stunted growth), Powdery mildew (white powdery spores on leaves), Citrus gummosis (fungal infection on trunk causing amber-colored gum). Nutritional Deficiencies: Nitrogen deficiency (light green to yellow foliage, yellow vein chlorosis). Pruning: Dead wood must be removed regularly. When trees become too big and start growing into one another, pruning is recommended. Branches touching the ground should be removed. Weeding: Keep the area under the canopy free from weeds as they compete for nutrients and water and harbour pathogens.",
    },
  },
  {
    id: "11",
    name: "Kumquat Oranges",
    price: 600,
    icon: "🍊",
    category: "citrus",
    careGuide: {
      watering: "Citrus trees should be planted in a sunny and wind-protected area. They can tolerate high temperatures provided the trees are well supplied with soil moisture. Moderate watering, drought tolerant. Water the plant after planting if soil isn't wet enough.",
      sunlight: "Full sun, 6+ hours daily. Citrus trees should be planted in a sunny and wind-protected area, and in frost-free regions because they cannot tolerate severe frosts.",
      soil: "Citrus can be grown in a wide range of soil types. However, for best results, they should be grown in well-drained soils, which are fertile, well-aerated and with a pH of between 6-6.5. The growth, development and production of citrus plant depends on the physical characteristics of the soil such as drainage, water-holding capacity, structure, soil depth, and the degree to which water can infiltrate the soil. Planting: Dig holes with dimensions 2 ft length by 2 ft width by 2 ft depth. Mix a bucket full of farmyard manure with topsoil at planting stage.",
      temperature: "Hardy, tolerates 5-32°C range. Citrus trees should be planted in frost-free regions because they cannot tolerate severe frosts. They can tolerate high temperatures provided the trees are well supplied with soil moisture.",
      fertilizer: "In order to remain healthy and produce optimally, the plants require sufficient nutrients, both macro and micronutrients. Nutrients that are needed in relatively large amounts are called the macronutrients. Basal and foliar fertilizers should therefore be applied in order to ensure effective nutrient supply to the plants. Light feeding, NPK 8-8-8.",
      spacing: "4m by 4m. 256 pieces per acre.",
      timeToFruit: "2.5 to 3 years.",
      pests: "Pests: False coddling moth (larvae burrow into fruit rind causing discoloration and premature ripening), Aphids (suck sap causing puckered marks, yellowing and twisting of leaves, honeydew excretion), Orange dog caterpillar (large 1.5-2 inch brown caterpillar that defoliates trees), Citrus whiteflies (tiny white winged insects feeding on underside of leaves, excrete honeydew), Fruit fly (adults deposit eggs under fruit skin, maggots feed on flesh causing rot), Citrus leafminer (larvae feed on young foliage creating silvery tunnels), Brown soft scale (small non-mobile insects attached to wood and foliage, cause yellowing and leaf drop), Citrus thrips (tiny orange or pale yellow insects causing shriveled buds and distorted leaves), Citrus bud mite (exceptionally small mite hiding in flower buds causing malformed growth). Diseases: Citrus canker (highly contagious bacterial infection with yellow halo-like lesions), Sooty mold (blackening fungus from honeydew secretions), Greasy spot (fungal disease with yellowish-brownish blister spots), Anthracnose (causes twig dieback and dark staining on fruit), Bacterial blast (black lesions in leaf petiole causing leaf curl and drop), Root Rot/Brown Rot/Collar rot (soil-inhabiting fungus causing dark brown patches on trunk), Citrus greening (bacterium spread by psyllids causing yellowing and stunted growth), Powdery mildew (white powdery spores on leaves), Citrus gummosis (fungal infection on trunk causing amber-colored gum). Nutritional Deficiencies: Nitrogen deficiency (light green to yellow foliage, yellow vein chlorosis). Pruning: Dead wood must be removed regularly. When trees become too big and start growing into one another, pruning is recommended. Branches touching the ground should be removed. Weeding: Keep the area under the canopy free from weeds as they compete for nutrients and water and harbour pathogens.",
    },
  },
  {
    id: "12",
    name: "Blood Orange",
    price: 500,
    icon: "🍊",
    category: "citrus",
    careGuide: {
      watering: "Citrus trees should be planted in a sunny and wind-protected area. They can tolerate high temperatures provided the trees are well supplied with soil moisture. Regular irrigation for good fruit quality. Water the plant after planting if soil isn't wet enough.",
      sunlight: "Full sun (8+ hours). Citrus trees should be planted in a sunny and wind-protected area, and in frost-free regions because they cannot tolerate severe frosts.",
      soil: "Citrus can be grown in a wide range of soil types. However, for best results, they should be grown in well-drained soils, which are fertile, well-aerated and with a pH of between 6-6.5. The growth, development and production of citrus plant depends on the physical characteristics of the soil such as drainage, water-holding capacity, structure, soil depth, and the degree to which water can infiltrate the soil. Planting: Dig holes with dimensions 2 ft length by 2 ft width by 2 ft depth. Mix a bucket full of farmyard manure with topsoil at planting stage.",
      temperature: "Warm (18-28°C). Citrus trees should be planted in frost-free regions because they cannot tolerate severe frosts. They can tolerate high temperatures provided the trees are well supplied with soil moisture.",
      fertilizer: "In order to remain healthy and produce optimally, the plants require sufficient nutrients, both macro and micronutrients. Nutrients that are needed in relatively large amounts are called the macronutrients. Basal and foliar fertilizers should therefore be applied in order to ensure effective nutrient supply to the plants. Apply citrus fertilizer 3x yearly.",
      spacing: "4m by 4m. 256 pieces per acre.",
      timeToFruit: "2.5 to 3 years.",
      pests: "Pests: False coddling moth (larvae burrow into fruit rind causing discoloration and premature ripening), Aphids (suck sap causing puckered marks, yellowing and twisting of leaves, honeydew excretion), Orange dog caterpillar (large 1.5-2 inch brown caterpillar that defoliates trees), Citrus whiteflies (tiny white winged insects feeding on underside of leaves, excrete honeydew), Fruit fly (adults deposit eggs under fruit skin, maggots feed on flesh causing rot), Citrus leafminer (larvae feed on young foliage creating silvery tunnels), Brown soft scale (small non-mobile insects attached to wood and foliage, cause yellowing and leaf drop), Citrus thrips (tiny orange or pale yellow insects causing shriveled buds and distorted leaves), Citrus bud mite (exceptionally small mite hiding in flower buds causing malformed growth). Diseases: Citrus canker (highly contagious bacterial infection with yellow halo-like lesions), Sooty mold (blackening fungus from honeydew secretions), Greasy spot (fungal disease with yellowish-brownish blister spots), Anthracnose (causes twig dieback and dark staining on fruit), Bacterial blast (black lesions in leaf petiole causing leaf curl and drop), Root Rot/Brown Rot/Collar rot (soil-inhabiting fungus causing dark brown patches on trunk), Citrus greening (bacterium spread by psyllids causing yellowing and stunted growth), Powdery mildew (white powdery spores on leaves), Citrus gummosis (fungal infection on trunk causing amber-colored gum). Nutritional Deficiencies: Nitrogen deficiency (light green to yellow foliage, yellow vein chlorosis). Pruning: Dead wood must be removed regularly. When trees become too big and start growing into one another, pruning is recommended. Branches touching the ground should be removed. Weeding: Keep the area under the canopy free from weeds as they compete for nutrients and water and harbour pathogens.",
    },
  },
  {
    id: "13",
    name: "Lime",
    price: 250,
    icon: "🍊",
    category: "citrus",
    careGuide: {
      watering: "Citrus trees should be planted in a sunny and wind-protected area. They can tolerate high temperatures provided the trees are well supplied with soil moisture. Consistent water, especially when fruiting. Water the plant after planting if soil isn't wet enough.",
      sunlight: "Full sun (6-8 hours). Citrus trees should be planted in a sunny and wind-protected area, and in frost-free regions because they cannot tolerate severe frosts.",
      soil: "Citrus can be grown in a wide range of soil types. However, for best results, they should be grown in well-drained soils, which are fertile, well-aerated and with a pH of between 6-6.5. The growth, development and production of citrus plant depends on the physical characteristics of the soil such as drainage, water-holding capacity, structure, soil depth, and the degree to which water can infiltrate the soil. Planting: Dig holes with dimensions 2 ft length by 2 ft width by 2 ft depth. Mix a bucket full of farmyard manure with topsoil at planting stage.",
      temperature: "Warm climate (20-32°C). Citrus trees should be planted in frost-free regions because they cannot tolerate severe frosts. They can tolerate high temperatures provided the trees are well supplied with soil moisture.",
      fertilizer: "In order to remain healthy and produce optimally, the plants require sufficient nutrients, both macro and micronutrients. Nutrients that are needed in relatively large amounts are called the macronutrients. Basal and foliar fertilizers should therefore be applied in order to ensure effective nutrient supply to the plants. NPK 10-5-5 or citrus fertilizer.",
      spacing: "4m by 4m. 256 pieces per acre.",
      timeToFruit: "2.5 to 3 years.",
      pests: "Pests: False coddling moth (larvae burrow into fruit rind causing discoloration and premature ripening), Aphids (suck sap causing puckered marks, yellowing and twisting of leaves, honeydew excretion), Orange dog caterpillar (large 1.5-2 inch brown caterpillar that defoliates trees), Citrus whiteflies (tiny white winged insects feeding on underside of leaves, excrete honeydew), Fruit fly (adults deposit eggs under fruit skin, maggots feed on flesh causing rot), Citrus leafminer (larvae feed on young foliage creating silvery tunnels), Brown soft scale (small non-mobile insects attached to wood and foliage, cause yellowing and leaf drop), Citrus thrips (tiny orange or pale yellow insects causing shriveled buds and distorted leaves), Citrus bud mite (exceptionally small mite hiding in flower buds causing malformed growth). Diseases: Citrus canker (highly contagious bacterial infection with yellow halo-like lesions), Sooty mold (blackening fungus from honeydew secretions), Greasy spot (fungal disease with yellowish-brownish blister spots), Anthracnose (causes twig dieback and dark staining on fruit), Bacterial blast (black lesions in leaf petiole causing leaf curl and drop), Root Rot/Brown Rot/Collar rot (soil-inhabiting fungus causing dark brown patches on trunk), Citrus greening (bacterium spread by psyllids causing yellowing and stunted growth), Powdery mildew (white powdery spores on leaves), Citrus gummosis (fungal infection on trunk causing amber-colored gum). Nutritional Deficiencies: Nitrogen deficiency (light green to yellow foliage, yellow vein chlorosis). Pruning: Dead wood must be removed regularly. When trees become too big and start growing into one another, pruning is recommended. Branches touching the ground should be removed. Weeding: Keep the area under the canopy free from weeds as they compete for nutrients and water and harbour pathogens.",
    },
  },
  {
    id: "14",
    name: "Sudachi Lemon",
    price: 2500,
    icon: "🍋",
    category: "citrus",
    careGuide: {
      watering: "Citrus trees should be planted in a sunny and wind-protected area. They can tolerate high temperatures provided the trees are well supplied with soil moisture. Regular watering, maintain moist soil. Water the plant after planting if soil isn't wet enough.",
      sunlight: "Full sun preferred. Citrus trees should be planted in a sunny and wind-protected area, and in frost-free regions because they cannot tolerate severe frosts.",
      soil: "Citrus can be grown in a wide range of soil types. However, for best results, they should be grown in well-drained soils, which are fertile, well-aerated and with a pH of between 6-6.5. The growth, development and production of citrus plant depends on the physical characteristics of the soil such as drainage, water-holding capacity, structure, soil depth, and the degree to which water can infiltrate the soil. Planting: Dig holes with dimensions 2 ft length by 2 ft width by 2 ft depth. Mix a bucket full of farmyard manure with topsoil at planting stage.",
      temperature: "Moderate warm (15-25°C). Citrus trees should be planted in frost-free regions because they cannot tolerate severe frosts. They can tolerate high temperatures provided the trees are well supplied with soil moisture.",
      fertilizer: "In order to remain healthy and produce optimally, the plants require sufficient nutrients, both macro and micronutrients. Nutrients that are needed in relatively large amounts are called the macronutrients. Basal and foliar fertilizers should therefore be applied in order to ensure effective nutrient supply to the plants. NPK 10-8-8 for citrus.",
      spacing: "4m by 4m. 256 pieces per acre.",
      timeToFruit: "2.5 to 3 years.",
      pests: "Pests: False coddling moth (larvae burrow into fruit rind causing discoloration and premature ripening), Aphids (suck sap causing puckered marks, yellowing and twisting of leaves, honeydew excretion), Orange dog caterpillar (large 1.5-2 inch brown caterpillar that defoliates trees), Citrus whiteflies (tiny white winged insects feeding on underside of leaves, excrete honeydew), Fruit fly (adults deposit eggs under fruit skin, maggots feed on flesh causing rot), Citrus leafminer (larvae feed on young foliage creating silvery tunnels), Brown soft scale (small non-mobile insects attached to wood and foliage, cause yellowing and leaf drop), Citrus thrips (tiny orange or pale yellow insects causing shriveled buds and distorted leaves), Citrus bud mite (exceptionally small mite hiding in flower buds causing malformed growth). Diseases: Citrus canker (highly contagious bacterial infection with yellow halo-like lesions), Sooty mold (blackening fungus from honeydew secretions), Greasy spot (fungal disease with yellowish-brownish blister spots), Anthracnose (causes twig dieback and dark staining on fruit), Bacterial blast (black lesions in leaf petiole causing leaf curl and drop), Root Rot/Brown Rot/Collar rot (soil-inhabiting fungus causing dark brown patches on trunk), Citrus greening (bacterium spread by psyllids causing yellowing and stunted growth), Powdery mildew (white powdery spores on leaves), Citrus gummosis (fungal infection on trunk causing amber-colored gum). Nutritional Deficiencies: Nitrogen deficiency (light green to yellow foliage, yellow vein chlorosis). Pruning: Dead wood must be removed regularly. When trees become too big and start growing into one another, pruning is recommended. Branches touching the ground should be removed. Weeding: Keep the area under the canopy free from weeds as they compete for nutrients and water and harbour pathogens.",
    },
  },
  {
    id: "15",
    name: "Lemon",
    price: 200,
    icon: "🍋",
    category: "citrus",
    careGuide: {
      watering: "Citrus trees should be planted in a sunny and wind-protected area. They can tolerate high temperatures provided the trees are well supplied with soil moisture. Regular watering, don't let soil dry out. Water the plant after planting if soil isn't wet enough.",
      sunlight: "Full sun (6+ hours). Citrus trees should be planted in a sunny and wind-protected area, and in frost-free regions because they cannot tolerate severe frosts.",
      soil: "Citrus can be grown in a wide range of soil types. However, for best results, they should be grown in well-drained soils, which are fertile, well-aerated and with a pH of between 6-6.5. The growth, development and production of citrus plant depends on the physical characteristics of the soil such as drainage, water-holding capacity, structure, soil depth, and the degree to which water can infiltrate the soil. Planting: Dig holes with dimensions 2 ft length by 2 ft width by 2 ft depth. Mix a bucket full of farmyard manure with topsoil at planting stage.",
      temperature: "Warm (18-28°C). Citrus trees should be planted in frost-free regions because they cannot tolerate severe frosts. They can tolerate high temperatures provided the trees are well supplied with soil moisture.",
      fertilizer: "In order to remain healthy and produce optimally, the plants require sufficient nutrients, both macro and micronutrients. Nutrients that are needed in relatively large amounts are called the macronutrients. Basal and foliar fertilizers should therefore be applied in order to ensure effective nutrient supply to the plants. Citrus fertilizer monthly during growing season.",
      spacing: "4m by 4m. 256 pieces per acre.",
      timeToFruit: "2.5 to 3 years.",
      pests: "Pests: False coddling moth (larvae burrow into fruit rind causing discoloration and premature ripening), Aphids (suck sap causing puckered marks, yellowing and twisting of leaves, honeydew excretion), Orange dog caterpillar (large 1.5-2 inch brown caterpillar that defoliates trees), Citrus whiteflies (tiny white winged insects feeding on underside of leaves, excrete honeydew), Fruit fly (adults deposit eggs under fruit skin, maggots feed on flesh causing rot), Citrus leafminer (larvae feed on young foliage creating silvery tunnels), Brown soft scale (small non-mobile insects attached to wood and foliage, cause yellowing and leaf drop), Citrus thrips (tiny orange or pale yellow insects causing shriveled buds and distorted leaves), Citrus bud mite (exceptionally small mite hiding in flower buds causing malformed growth). Diseases: Citrus canker (highly contagious bacterial infection with yellow halo-like lesions), Sooty mold (blackening fungus from honeydew secretions), Greasy spot (fungal disease with yellowish-brownish blister spots), Anthracnose (causes twig dieback and dark staining on fruit), Bacterial blast (black lesions in leaf petiole causing leaf curl and drop), Root Rot/Brown Rot/Collar rot (soil-inhabiting fungus causing dark brown patches on trunk), Citrus greening (bacterium spread by psyllids causing yellowing and stunted growth), Powdery mildew (white powdery spores on leaves), Citrus gummosis (fungal infection on trunk causing amber-colored gum). Nutritional Deficiencies: Nitrogen deficiency (light green to yellow foliage, yellow vein chlorosis). Pruning: Dead wood must be removed regularly. When trees become too big and start growing into one another, pruning is recommended. Branches touching the ground should be removed. Weeding: Keep the area under the canopy free from weeds as they compete for nutrients and water and harbour pathogens.",
    },
  },
  {
    id: "16",
    name: "Variagated Pink Lemon",
    price: 800,
    icon: "🍋",
    category: "citrus",
    careGuide: {
      watering: "Citrus trees should be planted in a sunny and wind-protected area. They can tolerate high temperatures provided the trees are well supplied with soil moisture. Regular watering, especially during fruiting. Water the plant after planting if soil isn't wet enough.",
      sunlight: "Full sun for best pink color. Citrus trees should be planted in a sunny and wind-protected area, and in frost-free regions because they cannot tolerate severe frosts.",
      soil: "Citrus can be grown in a wide range of soil types. However, for best results, they should be grown in well-drained soils, which are fertile, well-aerated and with a pH of between 6-6.5. The growth, development and production of citrus plant depends on the physical characteristics of the soil such as drainage, water-holding capacity, structure, soil depth, and the degree to which water can infiltrate the soil. Planting: Dig holes with dimensions 2 ft length by 2 ft width by 2 ft depth. Mix a bucket full of farmyard manure with topsoil at planting stage.",
      temperature: "Warm (18-28°C). Citrus trees should be planted in frost-free regions because they cannot tolerate severe frosts. They can tolerate high temperatures provided the trees are well supplied with soil moisture.",
      fertilizer: "In order to remain healthy and produce optimally, the plants require sufficient nutrients, both macro and micronutrients. Nutrients that are needed in relatively large amounts are called the macronutrients. Basal and foliar fertilizers should therefore be applied in order to ensure effective nutrient supply to the plants. Balanced NPK or citrus-specific.",
      spacing: "4m by 4m. 256 pieces per acre.",
      timeToFruit: "2.5 to 3 years.",
      pests: "Pests: False coddling moth (larvae burrow into fruit rind causing discoloration and premature ripening), Aphids (suck sap causing puckered marks, yellowing and twisting of leaves, honeydew excretion), Orange dog caterpillar (large 1.5-2 inch brown caterpillar that defoliates trees), Citrus whiteflies (tiny white winged insects feeding on underside of leaves, excrete honeydew), Fruit fly (adults deposit eggs under fruit skin, maggots feed on flesh causing rot), Citrus leafminer (larvae feed on young foliage creating silvery tunnels), Brown soft scale (small non-mobile insects attached to wood and foliage, cause yellowing and leaf drop), Citrus thrips (tiny orange or pale yellow insects causing shriveled buds and distorted leaves), Citrus bud mite (exceptionally small mite hiding in flower buds causing malformed growth). Diseases: Citrus canker (highly contagious bacterial infection with yellow halo-like lesions), Sooty mold (blackening fungus from honeydew secretions), Greasy spot (fungal disease with yellowish-brownish blister spots), Anthracnose (causes twig dieback and dark staining on fruit), Bacterial blast (black lesions in leaf petiole causing leaf curl and drop), Root Rot/Brown Rot/Collar rot (soil-inhabiting fungus causing dark brown patches on trunk), Citrus greening (bacterium spread by psyllids causing yellowing and stunted growth), Powdery mildew (white powdery spores on leaves), Citrus gummosis (fungal infection on trunk causing amber-colored gum). Nutritional Deficiencies: Nitrogen deficiency (light green to yellow foliage, yellow vein chlorosis). Pruning: Dead wood must be removed regularly. When trees become too big and start growing into one another, pruning is recommended. Branches touching the ground should be removed. Weeding: Keep the area under the canopy free from weeds as they compete for nutrients and water and harbour pathogens.",
    },
  },
  {
    id: "17",
    name: "Sweet Lemon",
    price: 350,
    icon: "🍋",
    category: "citrus",
    careGuide: {
      watering: "Citrus trees should be planted in a sunny and wind-protected area. They can tolerate high temperatures provided the trees are well supplied with soil moisture. Moderate, consistent watering. Water the plant after planting if soil isn't wet enough.",
      sunlight: "Full sun required. Citrus trees should be planted in a sunny and wind-protected area, and in frost-free regions because they cannot tolerate severe frosts.",
      soil: "Citrus can be grown in a wide range of soil types. However, for best results, they should be grown in well-drained soils, which are fertile, well-aerated and with a pH of between 6-6.5. The growth, development and production of citrus plant depends on the physical characteristics of the soil such as drainage, water-holding capacity, structure, soil depth, and the degree to which water can infiltrate the soil. Planting: Dig holes with dimensions 2 ft length by 2 ft width by 2 ft depth. Mix a bucket full of farmyard manure with topsoil at planting stage.",
      temperature: "Warm (20-32°C). Citrus trees should be planted in frost-free regions because they cannot tolerate severe frosts. They can tolerate high temperatures provided the trees are well supplied with soil moisture.",
      fertilizer: "In order to remain healthy and produce optimally, the plants require sufficient nutrients, both macro and micronutrients. Nutrients that are needed in relatively large amounts are called the macronutrients. Basal and foliar fertilizers should therefore be applied in order to ensure effective nutrient supply to the plants. NPK 8-8-8 or citrus fertilizer.",
      spacing: "4m by 4m. 256 pieces per acre.",
      timeToFruit: "2.5 to 3 years.",
      pests: "Pests: False coddling moth (larvae burrow into fruit rind causing discoloration and premature ripening), Aphids (suck sap causing puckered marks, yellowing and twisting of leaves, honeydew excretion), Orange dog caterpillar (large 1.5-2 inch brown caterpillar that defoliates trees), Citrus whiteflies (tiny white winged insects feeding on underside of leaves, excrete honeydew), Fruit fly (adults deposit eggs under fruit skin, maggots feed on flesh causing rot), Citrus leafminer (larvae feed on young foliage creating silvery tunnels), Brown soft scale (small non-mobile insects attached to wood and foliage, cause yellowing and leaf drop), Citrus thrips (tiny orange or pale yellow insects causing shriveled buds and distorted leaves), Citrus bud mite (exceptionally small mite hiding in flower buds causing malformed growth). Diseases: Citrus canker (highly contagious bacterial infection with yellow halo-like lesions), Sooty mold (blackening fungus from honeydew secretions), Greasy spot (fungal disease with yellowish-brownish blister spots), Anthracnose (causes twig dieback and dark staining on fruit), Bacterial blast (black lesions in leaf petiole causing leaf curl and drop), Root Rot/Brown Rot/Collar rot (soil-inhabiting fungus causing dark brown patches on trunk), Citrus greening (bacterium spread by psyllids causing yellowing and stunted growth), Powdery mildew (white powdery spores on leaves), Citrus gummosis (fungal infection on trunk causing amber-colored gum). Nutritional Deficiencies: Nitrogen deficiency (light green to yellow foliage, yellow vein chlorosis). Pruning: Dead wood must be removed regularly. When trees become too big and start growing into one another, pruning is recommended. Branches touching the ground should be removed. Weeding: Keep the area under the canopy free from weeds as they compete for nutrients and water and harbour pathogens.",
    },
  },

  // Avocado
  {
    id: "18",
    name: "Grafted Hass Avocado",
    price: 200,
    icon: "🥑",
    category: "avocado",
    careGuide: {
      watering: "Water the holes unless the soil is wet enough. Water the seedlings immediately after planting if it is not in the rainy season. Deep watering 1-2x weekly, don't overwater. Avoid waterlogged conditions as avocado plants are sensitive to excessive soil moisture.",
      sunlight: "Full sun (6+ hours) for good production. High temperatures and direct sunshine can cause sunburn damage to exposed fruits. Pruning should be minimized because the tree is very susceptible to sunburn.",
      soil: "Avocado grows successfully on many types of soil provided they are deep, with good water holding capacity and free draining. Water logged or saline soils are unsuitable because avocado plants are sensitive to excessive soil moisture and high salinity. The optimum pH is 5.5-6.5. Planting: Prepare planting holes about 60cm x 60cm x 60cm. Fill the holes with topsoil mixed with manure. Plant the grafts in the holes, to the same depth as they were in the nursery. The bud union should be about 300mm above the ground.",
      temperature: "Temperatures between 16-24 degrees centigrade are good for growing avocados and the maximum temperature for avocado is 33 degrees centigrade. Above this temperature the fruits and trees can be damaged. Avocado trees are not tolerant to frost especially those adapted to humid tropics. Altitude: 'Hass' is suited to altitudes 800-2100 m above sea level. The avocado tree requires high relative humidity at flowering, about 70-80 per cent, then moderate levels during the fruit swelling stage. Too much humidity encourages the proliferation of pests and diseases.",
      fertilizer: "To obtain good growth and high fruit yields, it is important to supply the plants with necessary nutrients. Basal and foliar fertilizers should be applied. NPK 8-3-9 for avocados, apply 3x yearly.",
      spacing: "5 metres by 5 metres. 150 pieces per acre.",
      timeToFruit: "3 years.",
      pests: "Pests: Fruit flies (various species attack avocados, lay eggs under skin of ripening fruit, cause sting lesions and star-shaped cracks), False coddling moth (young caterpillar tunnels into fruit causing discoloration, premature ripening and fruit drop), Thrips (small slender insects with fringed wings, feed by sucking plant sap, cause whitish/silvery damage, attacked fruits develop leathery brown skin), Scales (small stationary brown greenish insects, soft scales excrete honeydew leading to sooty mold, armored scales encrust twigs and leaves), Spider mites (produce circular necrotic spots with dense webbing, cause leaf distortion and drop), Bugs (coconut bug feeds on young and mature fruit causing necrotic bruise-like depressions, Helopeltis bugs feed on young tissue causing brown necrotic patches), Swarming leaf beetles (swarms cause severe damage to new terminal growth, damaged terminals have burnt look). Diseases: Avocado root rot/Phytophthora cinnamomi (attacks trees of any size, leaves become small pale/yellow green and wilted, branches die-back, feeder roots blackened and decayed), Anthracnose/Colletotrichum gloeosporioides (major post-harvest problem, appears as sunken spots on fruit, can penetrate deep into flesh, develops rapidly in storage), Scab/Sphaceloma perseae (infects young tissues, lesions appear as small dark spots giving corky appearance, fruits only susceptible when young), Cercospora leaf & fruit spot/Pseudocercospora purpurea (lesions appear as small light-yellow spots becoming reddish brown and hard, causes ragged holes in leaves), Bacterial soft rot/Erwinia carotovora (infected fruit has darkened metallic sheen, flesh is grey to black and soft with putrid smell), Stem end rot (dark brown to black rot begins at stem end, produces dark streaking of water-conducting tissues). Pruning: All suckers and dead branches are removed from main trunk branches. The canopy is pruned to keep the tree to a height of 5-8 m and for ease of picking. Pruning should however be minimized because the tree is very susceptible to sunburn. Weeding: The area around the tree should be kept clean by weeding and removal of all fallen fruits. Weeds compete for growth factors like nutrients and water and harbour pests and diseases.",
    },
  },
  {
    id: "19",
    name: "Grafted Fuerte Avocado",
    price: 200,
    icon: "🥑",
    category: "avocado",
    careGuide: {
      watering: "Water the holes unless the soil is wet enough. Water the seedlings immediately after planting if it is not in the rainy season. Water deeply, avoid waterlogging. Avoid waterlogged conditions as avocado plants are sensitive to excessive soil moisture.",
      sunlight: "Full sun required. High temperatures and direct sunshine can cause sunburn damage to exposed fruits. Pruning should be minimized because the tree is very susceptible to sunburn.",
      soil: "Avocado grows successfully on many types of soil provided they are deep, with good water holding capacity and free draining. Water logged or saline soils are unsuitable because avocado plants are sensitive to excessive soil moisture and high salinity. The optimum pH is 5.5-6.5. Planting: Prepare planting holes about 60cm x 60cm x 60cm. Fill the holes with topsoil mixed with manure. Plant the grafts in the holes, to the same depth as they were in the nursery. The bud union should be about 300mm above the ground.",
      temperature: "Temperatures between 16-24 degrees centigrade are good for growing avocados and the maximum temperature for avocado is 33 degrees centigrade. Above this temperature the fruits and trees can be damaged. Avocado trees are not tolerant to frost especially those adapted to humid tropics. Altitude: 'Fuerte' is suited to altitudes 1500-2100 m above sea level. The avocado tree requires high relative humidity at flowering, about 70-80 per cent, then moderate levels during the fruit swelling stage. Too much humidity encourages the proliferation of pests and diseases.",
      fertilizer: "To obtain good growth and high fruit yields, it is important to supply the plants with necessary nutrients. Basal and foliar fertilizers should be applied. NPK 8-3-9 or avocado-specific.",
      spacing: "5 metres by 5 metres. 150 pieces per acre.",
      timeToFruit: "3 years.",
      pests: "Pests: Fruit flies (various species attack avocados, lay eggs under skin of ripening fruit, cause sting lesions and star-shaped cracks), False coddling moth (young caterpillar tunnels into fruit causing discoloration, premature ripening and fruit drop), Thrips (small slender insects with fringed wings, feed by sucking plant sap, cause whitish/silvery damage, attacked fruits develop leathery brown skin), Scales (small stationary brown greenish insects, soft scales excrete honeydew leading to sooty mold, armored scales encrust twigs and leaves), Spider mites (produce circular necrotic spots with dense webbing, cause leaf distortion and drop), Bugs (coconut bug feeds on young and mature fruit causing necrotic bruise-like depressions, Helopeltis bugs feed on young tissue causing brown necrotic patches), Swarming leaf beetles (swarms cause severe damage to new terminal growth, damaged terminals have burnt look). Diseases: Avocado root rot/Phytophthora cinnamomi (attacks trees of any size, leaves become small pale/yellow green and wilted, branches die-back, feeder roots blackened and decayed), Anthracnose/Colletotrichum gloeosporioides (major post-harvest problem, appears as sunken spots on fruit, can penetrate deep into flesh, develops rapidly in storage), Scab/Sphaceloma perseae (infects young tissues, lesions appear as small dark spots giving corky appearance, fruits only susceptible when young), Cercospora leaf & fruit spot/Pseudocercospora purpurea (lesions appear as small light-yellow spots becoming reddish brown and hard, causes ragged holes in leaves), Bacterial soft rot/Erwinia carotovora (infected fruit has darkened metallic sheen, flesh is grey to black and soft with putrid smell), Stem end rot (dark brown to black rot begins at stem end, produces dark streaking of water-conducting tissues). Pruning: All suckers and dead branches are removed from main trunk branches. The canopy is pruned to keep the tree to a height of 5-8 m and for ease of picking. Pruning should however be minimized because the tree is very susceptible to sunburn. Weeding: The area around the tree should be kept clean by weeding and removal of all fallen fruits. Weeds compete for growth factors like nutrients and water and harbour pests and diseases.",
    },
  },

  // Berries
  {
    id: "20",
    name: "Strawberry",
    price: 150,
    icon: "🍓",
    category: "berries",
    careGuide: {
      watering: "Water is critically essential when growing strawberries. The plants need a lot of water especially when the runners and flowers are developing. Drip irrigation is highly recommended as it waters at the root. Keep soil consistently moist but not waterlogged. Strawberries are very easy to maintain.",
      sunlight: "Require 6-10 hours of direct sunlight each day. They do well in levelled or slightly higher grounds.",
      soil: "Strawberry farming does best in areas whose soil pH is 5.5-6.5. The soil should be well drained and weed-free. Planting: Till the land and remove weeds. Construct raised beds. Prepare planting holes deep enough to accommodate the entire root system without bending it. Plant seedlings at a spacing of 20 inches apart and 4 feet between rows. The roots should be covered, but the crown should be right at the soil surface.",
      temperature: "The crop thrives in hot climate and does not tolerate frost or extremely low temperatures. Strawberry farming in Kenya is done outdoors. However, for better performance, greenhouses are recommended because they protect the plants from drought and excess rain.",
      fertilizer: "Application of fertilizers and manure boost production. However, if too much fertilizer is applied, this promotes excessive leaf growth and poor production of flower stalks. Too much nitrogen results in soft and easily-damaged strawberries. NPK 5-10-10 during fruiting.",
      spacing: "20 inches apart and 4 feet between rows.",
      timeToFruit: "4-6 weeks after planting.",
      pests: "Pests: Strawberry bud weevil/Clipper (infestation leads to creation of holes in flowers and petals, stems are chewed or clipped through), Tarnished plant bugs (puncture plant tissue and suck sap leading to tissue distortion and premature leaf fall, secrete honeydew encouraging sooty mold), Strawberry thrips (adults and nymphs feed on leaves and flowers by sucking sap causing flower damage/abortion and malformed fruits), Nematodes (affected plants are stunted, older leaves die, few runners produced, roots may be short and stubby with swellings), Mites (infestation reduces plant vigour, plants appear retarded and distorted, leaves turn yellow with whitish feeding marks, silvery webbing visible), Aphids (feed through piercing and sucking plant sap resulting in distorted growth, excrete honeydew favoring sooty mold growth). Diseases: Leaf blight (occurs on older leaves, large circular to oval reddish-purple spots form, develop brown centers bordered by purple zones, black fungal growth in center), Leaf spot (symptoms begin as round purple spots on upper leaf surfaces, center becomes tan/gray then almost white with purple border, can attack petioles and fruit stalks), Leak (infected ripe berry remains unchanged at first then changes to light brown, becomes soft and watery and collapses flat with juice running out, covered with white fluffy cottony fungal growth), Leaf blotch (characterized by purplish to brown blotches and large necrotic spots, often wedge-shaped on leaflet ends, can attack fruit stalk and fruit), Gray mold/Botrytis (major fruit rot disease, starts as blossom blight, progresses to berries stems and leaves, covered with gray masses of spores in damp weather), Leathery rot (occurs on green or ripe fruits, rotted area is light brown in center shading into purple at edge, fruit becomes tough and leathery in late stages), Anthracnose fruit rot (symptoms appear as soft to firm brown to black spots on green fruits and dark purple spots on ripe fruits, spots enlarge rapidly, surface covered with pink to orange spore masses), Powdery mildew (causes infected leaflets to curl upwards along margins, lower leaf surface may turn reddish, fruit infection shows as tan to rusty pink berry surface that often cracks). Varieties: Chandler, Tribute, Tristar, Tioga Selva, Domail, Rabunda, Pajaro, Douglas. Cultural Practices: Mulching - after planting the strawberry plants, mulching the beds with pine needles, shredded leaves or straw helps to keep the soil temperature down, mitigate the weed problem, and also keeps the fruit cleaner by keeping the strawberries off of the dirt. As the mulch breaks down, it also adds organic matter to the soil. Weeding - weeds compete with the plants for nutrients, moisture, space and sunlight, as well as harbouring pathogens. Manual weeding is recommended. However, during critical growth periods, i.e., flowering, fruiting, daughter plant growth and establishment, weeding should not be done. This is in order to avoid any disturbances. Training - strawberries are sprawling plants and the seedlings send out runners. These runners should be trained in order to follow a specific pattern for better performance. Irrigation - water is critically essential when growing strawberries. The plants need a lot of water especially when the runners and flowers are developing. Drip irrigation is highly recommended as it waters at the root. Pruning - this is majorly aimed at increasing fruit production. Flowers should be pruned off immediately they appear.",
    },
  },
  {
    id: "21",
    name: "Raspberry",
    price: 600,
    icon: "🍓",
    category: "berries",
    careGuide: {
      watering: "Regular watering, 1-1.5 inches per week.",
      sunlight: "Full sun (6+ hours).",
      soil: "Well-drained, acidic soil (pH 5.5-6.8).",
      temperature: "Cool climate (10-20°C).",
      fertilizer: "NPK 10-10-20 during growing season.",
      spacing: "60-90 cm between plants.",
      timeToFruit: "6-8 weeks after planting.",
      pests: "Monitor for cane borer and spider mites.",
    },
  },
  {
    id: "22",
    name: "Blackberry",
    price: 700,
    icon: "🍓",
    category: "berries",
    careGuide: {
      watering: "Regular watering during growing season.",
      sunlight: "Full sun preferred (6+ hours).",
      soil: "Well-drained soil with organic matter.",
      temperature: "Moderate (12-22°C).",
      fertilizer: "NPK 10-5-20 during fruiting.",
      spacing: "1-1.5 meters between plants.",
      timeToFruit: "8-10 weeks after planting.",
      pests: "Watch for raspberry cane borer.",
    },
  },
  {
    id: "23",
    name: "Blueberry",
    price: 3000,
    icon: "🫐",
    category: "berries",
    careGuide: {
      watering: "Consistent moisture, 4-5 cm per week.",
      sunlight: "Full sun (6-8 hours) for best yields.",
      soil: "Acidic, well-drained soil (pH 4.5-5.8).",
      temperature: "Cool (10-18°C).",
      fertilizer: "Acid-forming NPK 10-10-10.",
      spacing: "1-1.5 meters.",
      timeToFruit: "2 years from transplant.",
      pests: "Relatively pest-resistant.",
    },
  },
  {
    id: "54",
    name: "Mulberry",
    price: 300,
    icon: "🍇",
    category: "berries",
    careGuide: {
      watering: "Moderate watering, drought tolerant.",
      sunlight: "Full sun preferred.",
      soil: "Well-drained soil.",
      temperature: "Warm (18-28°C).",
      fertilizer: "Minimal, NPK 8-8-8.",
      spacing: "4-5 meters.",
      timeToFruit: "1-2 years.",
      pests: "Generally pest-resistant.",
    },
  },

  // Tropical
  {
    id: "24",
    name: "Pawpaw",
    price: 150,
    icon: "🍈",
    category: "tropical",
    careGuide: {
      watering: "Water regularly, reduce in dry season.",
      sunlight: "Full sun (6-8 hours).",
      soil: "Well-drained loamy soil.",
      temperature: "Warm (20-32°C).",
      fertilizer: "NPK 10-5-5, apply quarterly.",
      spacing: "3-4 meters.",
      timeToFruit: "6-12 months from transplant.",
      pests: "Monitor for fruit flies.",
    },
  },
  {
    id: "25",
    name: "Grafted Tree Tomato",
    price: 200,
    icon: "🍅",
    category: "tropical",
    careGuide: {
      watering: "Water regularly, keep soil moist.",
      sunlight: "Full sun (6+ hours).",
      soil: "Well-drained, fertile soil.",
      temperature: "Warm (18-25°C).",
      fertilizer: "NPK 5-10-10 during fruiting.",
      spacing: "1.5-2 meters.",
      timeToFruit: "1 year.",
      pests: "Watch for caterpillars and mites.",
    },
  },
  {
    id: "26",
    name: "Dragon Fruit",
    price: 1000,
    icon: "🐉",
    category: "tropical",
    careGuide: {
      watering: "Moderate watering, drought tolerant.",
      sunlight: "Full sun (6-8 hours).",
      soil: "Well-drained, slightly acidic.",
      temperature: "Warm (20-30°C).",
      fertilizer: "NPK 6-6-6 or compost.",
      spacing: "2-3 meters.",
      timeToFruit: "2-3 years.",
      pests: "Generally pest-resistant.",
    },
  },
  {
    id: "27",
    name: "Tissue Culture Banana",
    price: 500,
    icon: "🍌",
    category: "tropical",
    careGuide: {
      watering: "Regular watering, maintain moist soil.",
      sunlight: "Full sun (6+ hours).",
      soil: "Rich, well-drained soil.",
      temperature: "Warm (20-30°C).",
      fertilizer: "NPK 10-10-20, apply monthly.",
      spacing: "2.5-3 meters.",
      timeToFruit: "6-9 months.",
      pests: "Monitor for banana weevil.",
    },
  },
  {
    id: "28",
    name: "Pears",
    price: 600,
    icon: "🍐",
    category: "tropical",
    careGuide: {
      watering: "Regular watering during growing season.",
      sunlight: "Full sun (6+ hours).",
      soil: "Well-drained loam.",
      temperature: "Moderate warm (15-25°C).",
      fertilizer: "NPK 10-5-5, apply 2x yearly.",
      spacing: "5-6 meters.",
      timeToFruit: "3-4 years.",
      pests: "Watch for pear slug.",
    },
  },
  {
    id: "29",
    name: "Giant Granadilla",
    price: 600,
    icon: "🍑",
    category: "tropical",
    careGuide: {
      watering: "Regular watering, avoid waterlogging.",
      sunlight: "Full sun for best fruit.",
      soil: "Well-drained, fertile soil.",
      temperature: "Warm (20-28°C).",
      fertilizer: "NPK 5-10-10 during fruiting.",
      spacing: "3-4 meters.",
      timeToFruit: "1-2 years.",
      pests: "Generally pest-resistant.",
    },
  },
  {
    id: "30",
    name: "Sweet Granadilla",
    price: 200,
    icon: "🍑",
    category: "tropical",
    careGuide: {
      watering: "Regular watering needed.",
      sunlight: "Full sun required.",
      soil: "Well-drained soil.",
      temperature: "Warm (18-28°C).",
      fertilizer: "Balanced NPK.",
      spacing: "2-3 meters.",
      timeToFruit: "1-2 years.",
      pests: "Monitor for common pests.",
    },
  },
  {
    id: "31",
    name: "Soursop",
    price: 400,
    icon: "🍑",
    category: "tropical",
    careGuide: {
      watering: "Regular watering, keep soil moist.",
      sunlight: "Full sun (6+ hours).",
      soil: "Well-drained, slightly acidic soil.",
      temperature: "Warm (20-30°C).",
      fertilizer: "NPK 10-5-5, apply 3x yearly.",
      spacing: "5-6 meters.",
      timeToFruit: "2-3 years.",
      pests: "Watch for scale insects.",
    },
  },
  {
    id: "32",
    name: "Custard Apple",
    price: 250,
    icon: "🍎",
    category: "tropical",
    careGuide: {
      watering: "Water regularly during growing season.",
      sunlight: "Full sun required.",
      soil: "Well-drained loamy soil.",
      temperature: "Warm (18-28°C).",
      fertilizer: "NPK 8-8-8, apply quarterly.",
      spacing: "6-8 meters.",
      timeToFruit: "3-4 years.",
      pests: "Monitor for fruit flies.",
    },
  },
  {
    id: "33",
    name: "Jabuticaba",
    price: 2000,
    icon: "🫐",
    category: "tropical",
    careGuide: {
      watering: "Keep soil consistently moist.",
      sunlight: "Full sun to partial shade.",
      soil: "Well-drained, acidic soil.",
      temperature: "Warm to moderate (15-28°C).",
      fertilizer: "Organic manure and NPK 8-8-8.",
      spacing: "4-5 meters.",
      timeToFruit: "3-5 years.",
      pests: "Relatively pest-resistant.",
    },
  },
  {
    id: "34",
    name: "Brazilian Cherry",
    price: 1500,
    icon: "🍒",
    category: "tropical",
    careGuide: {
      watering: "Moderate watering, allow to dry slightly.",
      sunlight: "Full sun (6+ hours).",
      soil: "Well-drained soil.",
      temperature: "Warm (20-30°C).",
      fertilizer: "NPK 10-5-5.",
      spacing: "3-4 meters.",
      timeToFruit: "2-3 years.",
      pests: "Generally hardy.",
    },
  },
  {
    id: "35",
    name: "Cherry Guava",
    price: 600,
    icon: "🍒",
    category: "tropical",
    careGuide: {
      watering: "Regular watering during growing season.",
      sunlight: "Full sun preferred.",
      soil: "Well-drained soil.",
      temperature: "Warm (20-28°C).",
      fertilizer: "NPK 10-5-5.",
      spacing: "2-3 meters.",
      timeToFruit: "1-2 years.",
      pests: "Monitor for guava weevil.",
    },
  },
  {
    id: "36",
    name: "White Sapote",
    price: 350,
    icon: "🍎",
    category: "tropical",
    careGuide: {
      watering: "Regular watering, drought tolerant once established.",
      sunlight: "Full sun (6+ hours).",
      soil: "Well-drained soil.",
      temperature: "Warm to moderate (15-28°C).",
      fertilizer: "NPK 8-8-8.",
      spacing: "6-8 meters.",
      timeToFruit: "3-5 years.",
      pests: "Relatively pest-free.",
    },
  },
  {
    id: "37",
    name: "Persimmon",
    price: 1500,
    icon: "🍊",
    category: "tropical",
    careGuide: {
      watering: "Moderate watering, drought tolerant.",
      sunlight: "Full sun required.",
      soil: "Well-drained soil.",
      temperature: "Cool to warm (10-28°C).",
      fertilizer: "NPK 10-5-5.",
      spacing: "6-8 meters.",
      timeToFruit: "3-4 years.",
      pests: "Generally pest-resistant.",
    },
  },
  {
    id: "38",
    name: "Jackfruit",
    price: 800,
    icon: "🍑",
    category: "tropical",
    careGuide: {
      watering: "Regular watering during growing season.",
      sunlight: "Full sun (6+ hours).",
      soil: "Well-drained, fertile soil.",
      temperature: "Warm (25-35°C).",
      fertilizer: "NPK 10-5-5, apply 3x yearly.",
      spacing: "8-10 meters.",
      timeToFruit: "3-5 years.",
      pests: "Monitor for fruit flies.",
    },
  },
  {
    id: "39",
    name: "Tamarind",
    price: 750,
    icon: "🍑",
    category: "tropical",
    careGuide: {
      watering: "Drought tolerant, minimal watering needed.",
      sunlight: "Full sun required.",
      soil: "Well-drained soil, any type.",
      temperature: "Warm (25-35°C).",
      fertilizer: "Minimal fertilizer requirements.",
      spacing: "8-10 meters.",
      timeToFruit: "5-7 years.",
      pests: "Generally pest-resistant.",
    },
  },
  {
    id: "40",
    name: "Fig Tree",
    price: 800,
    icon: "🍇",
    category: "tropical",
    careGuide: {
      watering: "Moderate watering, drought tolerant.",
      sunlight: "Full sun (6+ hours).",
      soil: "Well-drained soil.",
      temperature: "Warm (20-30°C).",
      fertilizer: "Minimal, apply NPK 5-10-10.",
      spacing: "4-5 meters.",
      timeToFruit: "1-2 years.",
      pests: "Generally pest-resistant.",
    },
  },

  // Other
  {
    id: "41",
    name: "Grafted Macadamia Muranga",
    price: 350,
    icon: "🌰",
    category: "tropical",
    careGuide: {
      watering: "Regular watering, drought tolerant.",
      sunlight: "Full sun (6+ hours).",
      soil: "Well-drained, slightly acidic soil.",
      temperature: "Warm (15-25°C).",
      fertilizer: "NPK 10-5-5.",
      spacing: "8-10 meters.",
      timeToFruit: "5-7 years.",
      pests: "Monitor for macadamia nut borer.",
    },
  },
  {
    id: "42",
    name: "Grafted Purple Passion",
    price: 200,
    icon: "💜",
    category: "tropical",
    careGuide: {
      watering: "Regular watering during growth.",
      sunlight: "Full sun required.",
      soil: "Well-drained soil.",
      temperature: "Warm (20-28°C).",
      fertilizer: "NPK 8-8-8.",
      spacing: "2-3 meters.",
      timeToFruit: "1-2 years.",
      pests: "Watch for passion fruit fly.",
    },
  },
  {
    id: "43",
    name: "Loquats",
    price: 300,
    icon: "🍊",
    category: "tropical",
    careGuide: {
      watering: "Moderate watering.",
      sunlight: "Full sun preferred.",
      soil: "Well-drained soil.",
      temperature: "Warm to cool (10-28°C).",
      fertilizer: "NPK 8-8-8.",
      spacing: "4-5 meters.",
      timeToFruit: "2-3 years.",
      pests: "Monitor for scale insects.",
    },
  },
  {
    id: "44",
    name: "Grapes",
    price: 350,
    icon: "🍇",
    category: "tropical",
    careGuide: {
      watering: "Regular watering, well-drained soil.",
      sunlight: "Full sun (6+ hours).",
      soil: "Well-drained, fertile loam.",
      temperature: "Moderate (10-28°C).",
      fertilizer: "NPK 10-5-5, apply 2x yearly.",
      spacing: "2-3 meters.",
      timeToFruit: "2-3 years.",
      pests: "Watch for powdery mildew.",
    },
  },
  {
    id: "45",
    name: "Apple",
    price: 1000,
    icon: "🍎",
    category: "tropical",
    careGuide: {
      watering: "Regular watering, 1 inch per week.",
      sunlight: "Full sun (6+ hours).",
      soil: "Well-drained loam.",
      temperature: "Cool to moderate (10-20°C).",
      fertilizer: "NPK 10-5-5, apply yearly.",
      spacing: "4-6 meters.",
      timeToFruit: "2-3 years.",
      pests: "Watch for codling moth.",
    },
  },
  {
    id: "46",
    name: "Guavas",
    price: 150,
    icon: "🍈",
    category: "tropical",
    careGuide: {
      watering: "Moderate watering, drought tolerant.",
      sunlight: "Full sun required.",
      soil: "Well-drained soil, any type.",
      temperature: "Warm (20-30°C).",
      fertilizer: "Minimal fertilizer needed.",
      spacing: "3-4 meters.",
      timeToFruit: "1-2 years.",
      pests: "Monitor for scale insects.",
    },
  },
  {
    id: "47",
    name: "Kiwi",
    price: 500,
    icon: "🥝",
    category: "tropical",
    careGuide: {
      watering: "Regular watering, especially in growing season.",
      sunlight: "Full sun (6+ hours).",
      soil: "Well-drained, slightly acidic soil.",
      temperature: "Cool to moderate (10-20°C).",
      fertilizer: "NPK 10-5-5.",
      spacing: "4-5 meters.",
      timeToFruit: "3-4 years.",
      pests: "Monitor for root rot.",
    },
  },
  {
    id: "48",
    name: "Pomegranate",
    price: 500,
    icon: "🍎",
    category: "tropical",
    careGuide: {
      watering: "Moderate watering, drought tolerant.",
      sunlight: "Full sun (6+ hours).",
      soil: "Well-drained soil.",
      temperature: "Warm (20-32°C).",
      fertilizer: "NPK 10-5-5.",
      spacing: "2-3 meters.",
      timeToFruit: "2-3 years.",
      pests: "Generally pest-resistant.",
    },
  },
  {
    id: "49",
    name: "Plums",
    price: 500,
    icon: "🍑",
    category: "tropical",
    careGuide: {
      watering: "Regular watering during growing season.",
      sunlight: "Full sun (6+ hours).",
      soil: "Well-drained loam.",
      temperature: "Cool to moderate (10-25°C).",
      fertilizer: "NPK 10-5-5.",
      spacing: "4-5 meters.",
      timeToFruit: "2-3 years.",
      pests: "Watch for plum curculio.",
    },
  },
  {
    id: "50",
    name: "Peaches",
    price: 3000,
    icon: "🍑",
    category: "tropical",
    careGuide: {
      watering: "Regular watering, consistent moisture.",
      sunlight: "Full sun required.",
      soil: "Well-drained loamy soil.",
      temperature: "Cool climate needed for dormancy.",
      fertilizer: "NPK 10-10-10.",
      spacing: "4-5 meters.",
      timeToFruit: "2-3 years.",
      pests: "Monitor for brown rot.",
    },
  },
  {
    id: "51",
    name: "Zambarau",
    price: 800,
    icon: "🍑",
    category: "tropical",
    careGuide: {
      watering: "Moderate watering needed.",
      sunlight: "Full sun.",
      soil: "Well-drained soil.",
      temperature: "Warm (20-28°C).",
      fertilizer: "NPK 8-8-8.",
      spacing: "4-5 meters.",
      timeToFruit: "3-4 years.",
      pests: "Standard pest management.",
    },
  },
  {
    id: "52",
    name: "Cashewnut",
    price: 800,
    icon: "🥜",
    category: "tropical",
    careGuide: {
      watering: "Drought tolerant, minimal watering.",
      sunlight: "Full sun (6+ hours).",
      soil: "Well-drained, sandy soil preferred.",
      temperature: "Warm (25-35°C).",
      fertilizer: "NPK 10-5-5.",
      spacing: "7-8 meters.",
      timeToFruit: "5-6 years.",
      pests: "Monitor for cashew leaf miner.",
    },
  },
  {
    id: "53",
    name: "Olive",
    price: 1000,
    icon: "🫒",
    category: "tropical",
    careGuide: {
      watering: "Drought tolerant, minimal watering.",
      sunlight: "Full sun required.",
      soil: "Well-drained, slightly alkaline soil.",
      temperature: "Warm to cool (10-28°C).",
      fertilizer: "NPK 10-5-10.",
      spacing: "6-8 meters.",
      timeToFruit: "4-6 years.",
      pests: "Generally pest-resistant.",
    },
  },
  {
    id: "55",
    name: "Dwarf Coconut",
    price: 1000,
    icon: "🥥",
    category: "tropical",
    careGuide: {
      watering: "Regular watering, especially when young.",
      sunlight: "Full sun (6+ hours).",
      soil: "Well-drained, sandy soil.",
      temperature: "Warm (25-32°C).",
      fertilizer: "NPK 10-10-10, apply 3x yearly.",
      spacing: "3-4 meters.",
      timeToFruit: "4-6 years.",
      pests: "Monitor for coconut mite.",
    },
  },
  // Flower Seedlings
  {
    id: "56",
    name: "Roses (Hybrid Tea)",
    price: 350,
    icon: "🌹",
    category: "flowers",
    careGuide: {
      watering: "Water deeply 2-3 times per week. Keep soil moist but not waterlogged.",
      sunlight: "Full sun (6-8 hours daily) for best blooms.",
      soil: "Well-drained, fertile soil with pH 6.0-6.5. Add compost.",
      temperature: "Moderate (15-25°C). Protect from extreme heat.",
      fertilizer: "Apply rose fertilizer monthly during growing season.",
      spacing: "60-90cm apart for optimal growth.",
      timeToFruit: "Blooms in 3-4 months. Continuous flowering.",
      pests: "Watch for aphids, black spot, and powdery mildew. Use organic sprays.",
    },
  },
  {
    id: "57",
    name: "Hibiscus (Tropical)",
    price: 250,
    icon: "🌺",
    category: "flowers",
    careGuide: {
      watering: "Water regularly, keep soil consistently moist.",
      sunlight: "Full sun to partial shade (4-6 hours).",
      soil: "Well-drained, rich organic soil.",
      temperature: "Warm (20-30°C). Frost-sensitive.",
      fertilizer: "Apply balanced fertilizer every 2-3 months.",
      spacing: "1-2 meters apart.",
      timeToFruit: "Blooms in 2-3 months. Year-round flowering.",
      pests: "Monitor for aphids and whiteflies. Use neem oil.",
    },
  },
  {
    id: "58",
    name: "Bougainvillea",
    price: 300,
    icon: "🌸",
    category: "flowers",
    careGuide: {
      watering: "Water deeply but infrequently. Drought tolerant once established.",
      sunlight: "Full sun (6+ hours) for vibrant blooms.",
      soil: "Well-drained soil. Can tolerate poor soil conditions.",
      temperature: "Warm (20-30°C). Protect from frost.",
      fertilizer: "Apply low-nitrogen fertilizer monthly during blooming.",
      spacing: "2-3 meters apart for climbers.",
      timeToFruit: "Blooms in 4-6 months. Year-round flowering.",
      pests: "Generally pest-resistant. Watch for aphids.",
    },
  },
  {
    id: "59",
    name: "Frangipani (Plumeria)",
    price: 400,
    icon: "🌼",
    category: "flowers",
    careGuide: {
      watering: "Water moderately. Allow soil to dry between waterings.",
      sunlight: "Full sun (6+ hours) for best flowering.",
      soil: "Well-drained, sandy soil with good drainage.",
      temperature: "Warm (20-30°C). Protect from cold.",
      fertilizer: "Apply high-phosphorus fertilizer during growing season.",
      spacing: "3-4 meters apart.",
      timeToFruit: "Blooms in 2-3 years. Seasonal flowering.",
      pests: "Generally pest-resistant. Watch for rust and scale.",
    },
  },
  {
    id: "60",
    name: "Jasmine (Arabian)",
    price: 280,
    icon: "🌿",
    category: "flowers",
    careGuide: {
      watering: "Keep soil consistently moist, especially in summer.",
      sunlight: "Full sun to partial shade (4-6 hours).",
      soil: "Well-drained, fertile soil with organic matter.",
      temperature: "Warm (18-30°C). Protect from frost.",
      fertilizer: "Apply balanced fertilizer monthly during growing season.",
      spacing: "1-2 meters apart for climbers.",
      timeToFruit: "Blooms in 6-12 months. Fragrant night blooms.",
      pests: "Watch for aphids and spider mites. Use organic sprays.",
    },
  },
  {
    id: "61",
    name: "Marigold (African)",
    price: 150,
    icon: "🌻",
    category: "flowers",
    careGuide: {
      watering: "Water regularly but avoid overwatering. Let soil dry slightly.",
      sunlight: "Full sun (6+ hours) for best blooms.",
      soil: "Well-drained, fertile soil. Tolerates various soil types.",
      temperature: "Warm (18-27°C). Heat tolerant.",
      fertilizer: "Apply balanced fertilizer every 4-6 weeks.",
      spacing: "30-45cm apart.",
      timeToFruit: "Blooms in 6-8 weeks. Continuous flowering.",
      pests: "Natural pest repellent. Generally pest-free.",
    },
  },
  {
    id: "62",
    name: "Sunflower (Giant)",
    price: 200,
    icon: "🌻",
    category: "flowers",
    careGuide: {
      watering: "Water deeply once or twice per week.",
      sunlight: "Full sun (6-8 hours) essential for growth.",
      soil: "Well-drained, fertile soil. Can tolerate various pH levels.",
      temperature: "Warm (18-27°C). Heat tolerant.",
      fertilizer: "Apply balanced fertilizer at planting and mid-season.",
      spacing: "45-60cm apart for large varieties.",
      timeToFruit: "Blooms in 10-12 weeks. Single season.",
      pests: "Watch for birds and squirrels. Generally pest-resistant.",
    },
  },
  {
    id: "63",
    name: "Lantana (Colorful)",
    price: 180,
    icon: "🌺",
    category: "flowers",
    careGuide: {
      watering: "Water regularly, drought tolerant once established.",
      sunlight: "Full sun (6+ hours) for best flowering.",
      soil: "Well-drained soil. Tolerates poor soil.",
      temperature: "Warm (20-30°C). Heat and drought tolerant.",
      fertilizer: "Apply balanced fertilizer monthly during growing season.",
      spacing: "60-90cm apart.",
      timeToFruit: "Blooms in 2-3 months. Year-round flowering.",
      pests: "Generally pest-resistant. Attracts butterflies.",
    },
  },
  {
    id: "64",
    name: "Petunia (Grandiflora)",
    price: 120,
    icon: "🌷",
    category: "flowers",
    careGuide: {
      watering: "Water regularly, keep soil moist but not soggy.",
      sunlight: "Full sun to partial shade (4-6 hours).",
      soil: "Well-drained, fertile soil with good organic content.",
      temperature: "Moderate (15-25°C). Protect from extreme heat.",
      fertilizer: "Apply liquid fertilizer every 2 weeks during blooming.",
      spacing: "30-45cm apart.",
      timeToFruit: "Blooms in 6-8 weeks. Continuous flowering.",
      pests: "Watch for aphids and slugs. Use organic controls.",
    },
  },
  {
    id: "65",
    name: "Zinnia (Giant)",
    price: 140,
    icon: "🌼",
    category: "flowers",
    careGuide: {
      watering: "Water at base, avoid wetting leaves. Moderate watering.",
      sunlight: "Full sun (6+ hours) for best blooms.",
      soil: "Well-drained, fertile soil. Tolerates various conditions.",
      temperature: "Warm (18-27°C). Heat tolerant.",
      fertilizer: "Apply balanced fertilizer at planting.",
      spacing: "30-45cm apart.",
      timeToFruit: "Blooms in 6-8 weeks. Long-lasting cut flowers.",
      pests: "Generally pest-resistant. Watch for powdery mildew.",
    },
  },
]
